<?php

namespace Monstrex\Ave\Core\Components;

use Illuminate\Support\Str;
use Monstrex\Ave\Core\FormContext;

/**
 * Tab component - individual tab inside Tabs container
 *
 * Example:
 * ```php
 * Tab::make('General')
 *     ->icon('fa fa-info-circle')
 *     ->badge('New')
 *     ->schema([...])
 * ```
 */
class Tab extends ComponentContainer
{
    protected string $id;

    protected string $label;

    protected ?string $icon = null;

    protected ?string $badge = null;

    protected function getDefaultViewTemplate(): string
    {
        return 'ave::components.forms.tab-panel';
    }

    public function __construct(string $label)
    {
        $this->label = $label;
        // Generate unique tab ID
        $this->id = 'tab-' . Str::slug($label ?: Str::random(6)) . '-' . substr(md5(spl_object_hash($this)), 0, 6);
    }

    public static function make(string $label, array $components = []): static
    {
        $instance = new static($label);

        if ($components) {
            $instance->schema($components);
        }

        return $instance;
    }

    /**
     * Override the tab ID (auto-generated by default)
     */
    public function id(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Set icon for the tab header
     */
    public function icon(?string $icon): static
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * Set badge text (e.g., for notifications)
     */
    public function badge(?string $badge): static
    {
        $this->badge = $badge;

        return $this;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function getBadge(): ?string
    {
        return $this->badge;
    }

    public function render(FormContext $context): string
    {
        return view($this->getViewTemplate(), [
            'tab' => $this,
            'context' => $context,
            'content' => $this->renderChildComponents($context),
        ])->render();
    }
}
